#
# Makefile for ALSA driver for AtHome remote control.
# (C) 2013 Google Inc
#

snd-mic-btle-sbc-objs := mic_btle_sbc.o
snd-sbcdec-objs := sbcdec.o

obj-$(CONFIG_SND_MIC_BTLE_SBC) += snd-mic-btle-sbc.o
obj-$(CONFIG_SND_MIC_BTLE_SBC) += snd-sbcdec.o
